language: python
sudo: false

env:
  global:
    # Doctr deploy key for NSLS-II/NSLS-II.github.io
    - secure: "vJnQwcJw7t9fSS3A/u3JXjXVLErDKIPcAnwx4HaKhuPmXB8Mq5455jSJvK65DOl7Wh4q1WvHGiFdTJ7JtHOxyTCCAJQBElzhT4/6IjjgrqG5s5HIN/qyACimpeXLCdM0FslyCu4bpt0TTd/FReV0Oq3pHt1FiQkpBq07W0t1NvrSv4lymtadT6ZgVlVOFGOcbmUH6sdexBm4TSJnVJjFva8v11zaICFXCIm1PRAraj5ueBm13SpozQ6lZA0e2aOnMqgQg3cId3Hag1SzYmZeYZ8F0ZzCDOX4grbu0S5tUacz0RxieJpx3TTP3lLEXyJvkmFIwuV8aPquZZpVxtzksHnUwED4B0icSVJ1WGMw8hCQpxRHYf9W2wqlIzYb7p3eBhnbl0zrdf6+hMwRontI7HhBnqbEvWpBJArYcaYEMfw714i63bJiD7fZLZ+8Nz7pjwKxhD6dF2ZR37MPAkKeGt3Z/QfAZBZ++hW2mPxSMEMUjGX7FJsMCuryNzVDqKGk3vLc2k+OKU+DjnJyYZq+00defVfjJL0Hh4ZUnC0C97MwLgeHiC9jLcnhdqTg5U12muj4eQJ1roolNTgkjbyS8FLA2kmAVft04hgaqKg/FaAvlpxMAASwkaKO8C7Kz7TDQ8SwxpX0S1qpmd/gblbMHl0k1jfqnwoYRHxJ3jb8Whs="
    # Doctr deploy key for bluesky/bluesky.github.io
    - secure: "spb6HwGVvMPsQw9cEwJscmAlG7seL0svW8ouYlDr4OESJJJqC8bynEpAl7Zm/NuKiZ701IR9gEBFuwCRoEXNJ6AkqgBE0DOMj4Oezg4eUnaZz0aXJ+C6mz31vbcNmU6MrjSElw80cIXBpia3j//VMluMzJMsGx/ELPATu2nwyx1+KXljGpFe1/7HYcq/wFHi+sC02sZRVYJGqrb5Zms35hlk4xasWKlsgLh53kW+ss+4hY67vllL2iRkYiP+8z4e3dTOuDqJWx5lLT16wt0K+wJyP/QTyIP81tmMNoWRbdrfOrzyyVXZDbrlzpZDBRtvlMFMHOeEZOrFPIYuclEjT39Tge+T/OxR6SC8kvzqVItxyxLEKWpQu8DHRVEDAuirteuv4IKEnS80nbWn4v/sBOU+sC0/23dW9zZkMrNmRoSFcjudmy2PGIY8jxzOhGJJ+Rbi0xIaKwdLbDZoPHM3m9m2uWYfGNMBHDgnh/HDIq71zzYWaW4gChYgU0UeDM1RYnr1XRa44znlZ0YLnmEyxn/5LzH/hRDxqc5XH5OAiKLnTddZFYsvdRT1JMNSA5PRSm7E8BCvCOEwovjnvRUc0dktyd8+OC5+Eyf1neJ6M7F2sGxCi3yMKw3VmfCxINu6XO3GsPE7cKACEq0lriCxjNzFWbedOX9dTL1Uqdc3pQA="


cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - mongodb-org

before_install:
  - export TZ=US/Eastern

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      env: PUBLISH_DOCS=1
    - python: nightly
  allow_failures:
    - python: nightly

install:
  - pip install --upgrade cython
  - pip install --quiet --upgrade --global-option='--without-libyaml' pyyaml
  - pip install -U .[all]
  - pip install -Ur test-requirements.txt
  - pip install codecov

script:
  - coverage run run_tests.py
  - coverage report -m
  - set -e
  - pip install -Ur docs-requirements.txt
  - make -C doc html
  - |
    if [ $PUBLISH_DOCS ]; then
      # Push built documentation to GH pages.
      pip install doctr
      doctr deploy --deploy-repo NSLS-II/NSLS-II.github.io --deploy-branch-name master databroker
      doctr deploy --deploy-repo bluesky/bluesky.github.io --deploy-branch-name master databroker
    fi

after_success:
  - codecov
